import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import Layout from "@/components/layout/Layout";
import SEO from "@/components/SEO";
import { tools } from "@/data/tools";

const Tools = () => {
  const toolCategories = [...new Set(tools.map(t => t.category))];

  return (
    <Layout>
      <SEO
        title="Free AI Developer Tools — Code, Security & SEO"
        description="Free AI-powered developer tools: code snippet generator, vulnerability explainer, SEO meta tag generator, regex tester, password checker, smart contract auditor, and more. No signup required."
        keywords="free developer tools, AI code generator, vulnerability scanner, SEO meta generator, regex tester online, password strength checker, smart contract auditor, cloud architecture tool, code explainer, prompt engineering templates"
        canonical="/tools"
        breadcrumbs={[
          { name: "Home", path: "/" },
          { name: "Tools", path: "/tools" },
        ]}
        faqJsonLd={[
          { question: "Are CodeSecAI tools free to use?", answer: "Yes, all AI-powered tools on CodeSecAI are completely free with no signup or account required." },
          { question: "What types of developer tools does CodeSecAI offer?", answer: "CodeSecAI offers code generators, vulnerability explainers, SEO analyzers, regex testers, cloud architecture planners, and more — all powered by AI." },
          { question: "Do I need to create an account to use the tools?", answer: "No. All tools are available instantly without registration, login, or any personal information." },
          { question: "How do the AI-powered tools work?", answer: "Our tools use advanced AI models to analyze your input — whether it's code, security configurations, or architecture diagrams — and provide actionable insights, suggestions, or generated output in real time." },
          { question: "Can I use these tools for commercial projects?", answer: "Yes. The output generated by our tools can be used freely in both personal and commercial projects." },
        ]}
      />
      <section className="hero-gradient">
        <div className="container py-16 text-center">
          <h1 className="text-3xl md:text-4xl font-bold text-foreground mb-3">Free AI-Powered Developer Tools</h1>
          <p className="text-muted-foreground max-w-2xl mx-auto">Code generators, vulnerability explainers, SEO analyzers, regex testers, and more — all free, no signup required.</p>
        </div>
      </section>
      <div className="container py-12">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {tools.map((tool, i) => (
            <motion.div key={tool.id} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.05 }}>
              <Link to={`/tools/${tool.slug}`} className="block group">
                <div className="bg-card border rounded-lg p-6 hover:shadow-md hover:border-primary/30 transition-all h-full">
                  <div className="flex items-start justify-between mb-3">
                    <span className="text-3xl">{tool.icon}</span>
                    <span className="text-xs font-medium text-primary bg-primary/10 rounded-full px-2.5 py-0.5">{tool.category}</span>
                  </div>
                  <h3 className="font-bold text-foreground group-hover:text-primary transition-colors mb-2">{tool.name}</h3>
                  <p className="text-sm text-muted-foreground">{tool.description}</p>
                  {tool.isClientOnly && <span className="inline-block mt-3 text-xs text-secondary font-medium">✓ Runs locally — no data sent to servers</span>}
                </div>
              </Link>
            </motion.div>
          ))}
        </div>
      </div>
    </Layout>
  );
};

export default Tools;
