import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "@/hooks/use-toast";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";

const templates: Record<string, { base: string; install: string; build: string; cmd: string; port: number }> = {
  "Node.js": { base: "node:20-alpine", install: "COPY package*.json ./\nRUN npm ci --only=production", build: "COPY . .\nRUN npm run build", cmd: 'CMD ["node", "dist/index.js"]', port: 3000 },
  "Python": { base: "python:3.12-slim", install: "COPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt", build: "COPY . .", cmd: 'CMD ["python", "app.py"]', port: 8000 },
  "Go": { base: "golang:1.22-alpine AS builder", install: "COPY go.mod go.sum ./\nRUN go mod download", build: "COPY . .\nRUN CGO_ENABLED=0 GOOS=linux go build -o /app", cmd: 'CMD ["/app"]', port: 8080 },
  "Rust": { base: "rust:1.77-slim AS builder", install: "COPY Cargo.toml Cargo.lock ./\nRUN mkdir src && echo 'fn main(){}' > src/main.rs && cargo build --release", build: "COPY . .\nRUN cargo build --release", cmd: 'CMD ["./target/release/app"]', port: 8080 },
  "Java": { base: "eclipse-temurin:21-jdk-alpine AS builder", install: "COPY pom.xml .\nRUN mvn dependency:go-offline", build: "COPY . .\nRUN mvn package -DskipTests", cmd: 'CMD ["java", "-jar", "target/app.jar"]', port: 8080 },
  "Static (Nginx)": { base: "nginx:alpine", install: "", build: "COPY ./dist /usr/share/nginx/html\nCOPY nginx.conf /etc/nginx/conf.d/default.conf", cmd: 'CMD ["nginx", "-g", "daemon off;"]', port: 80 },
};

const DockerfileGenerator = () => {
  const [runtime, setRuntime] = useState("Node.js");
  const [appName, setAppName] = useState("my-app");
  const [multiStage, setMultiStage] = useState(true);
  const [nonRoot, setNonRoot] = useState(true);
  const [healthCheck, setHealthCheck] = useState(true);
  const [dockerfile, setDockerfile] = useState("");

  const generate = () => {
    const t = templates[runtime];
    const lines: string[] = [];

    lines.push(`# ${appName} - ${runtime} Dockerfile`);
    lines.push(`# Generated by CodeSecAI Tools\n`);

    if (multiStage && ["Go", "Rust", "Java"].includes(runtime)) {
      lines.push(`FROM ${t.base}`);
      lines.push(`WORKDIR /build\n`);
      lines.push(t.install);
      lines.push(t.build);
      lines.push(`\n# --- Production Stage ---`);
      lines.push(runtime === "Go" || runtime === "Rust" ? `FROM alpine:3.19` : `FROM eclipse-temurin:21-jre-alpine`);
      lines.push(`WORKDIR /app`);
      if (runtime === "Go") lines.push(`COPY --from=builder /app .`);
      else if (runtime === "Rust") lines.push(`COPY --from=builder /build/target/release/app .`);
      else lines.push(`COPY --from=builder /build/target/app.jar .`);
    } else {
      lines.push(`FROM ${t.base}`);
      lines.push(`WORKDIR /app\n`);
      if (t.install) lines.push(t.install);
      lines.push(t.build);
    }

    if (nonRoot) {
      lines.push(`\n# Security: Run as non-root user`);
      lines.push(`RUN addgroup -S appgroup && adduser -S appuser -G appgroup`);
      lines.push(`USER appuser`);
    }

    lines.push(`\nEXPOSE ${t.port}`);

    if (healthCheck) {
      lines.push(`\nHEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\`);
      lines.push(`  CMD wget --no-verbose --tries=1 --spider http://localhost:${t.port}/health || exit 1`);
    }

    lines.push(`\n${t.cmd}`);
    setDockerfile(lines.join("\n"));
  };

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div>
          <p className="text-xs text-muted-foreground mb-1">Runtime</p>
          <Select value={runtime} onValueChange={setRuntime}>
            <SelectTrigger><SelectValue /></SelectTrigger>
            <SelectContent>{Object.keys(templates).map(r => <SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent>
          </Select>
        </div>
        <div>
          <p className="text-xs text-muted-foreground mb-1">App Name</p>
          <Input value={appName} onChange={e => setAppName(e.target.value)} />
        </div>
      </div>

      <div className="flex flex-wrap gap-6">
        <div className="flex items-center gap-2"><Switch checked={multiStage} onCheckedChange={setMultiStage} /><Label className="text-sm">Multi-stage build</Label></div>
        <div className="flex items-center gap-2"><Switch checked={nonRoot} onCheckedChange={setNonRoot} /><Label className="text-sm">Non-root user</Label></div>
        <div className="flex items-center gap-2"><Switch checked={healthCheck} onCheckedChange={setHealthCheck} /><Label className="text-sm">Health check</Label></div>
      </div>

      <Button onClick={generate}>Generate Dockerfile</Button>

      {dockerfile && (
        <div className="mt-4 space-y-3">
          <div className="flex items-center justify-between">
            <Badge variant="secondary">{runtime}</Badge>
            <Button variant="outline" size="sm" onClick={() => { navigator.clipboard.writeText(dockerfile); toast({ title: "Dockerfile copied!" }); }}>Copy</Button>
          </div>
          <pre className="bg-muted/50 border rounded-xl p-4 text-sm font-mono text-foreground whitespace-pre-wrap overflow-x-auto max-h-96">{dockerfile}</pre>
        </div>
      )}
    </div>
  );
};

export default DockerfileGenerator;
