import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Copy, Plus, Trash2 } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

interface RobotsRule {
  userAgent: string;
  allow: string[];
  disallow: string[];
}

const RobotsTxtGenerator = () => {
  const [rules, setRules] = useState<RobotsRule[]>([{ userAgent: "*", allow: ["/"], disallow: ["/admin/", "/api/", "/private/"] }]);
  const [sitemapUrl, setSitemapUrl] = useState("");
  const [crawlDelay, setCrawlDelay] = useState("");
  const [hostUrl, setHostUrl] = useState("");

  const addRule = () => {
    setRules([...rules, { userAgent: "Googlebot", allow: ["/"], disallow: [] }]);
  };

  const removeRule = (idx: number) => {
    setRules(rules.filter((_, i) => i !== idx));
  };

  const updateUserAgent = (idx: number, value: string) => {
    setRules(rules.map((r, i) => (i === idx ? { ...r, userAgent: value } : r)));
  };

  const addPath = (ruleIdx: number, type: "allow" | "disallow") => {
    setRules(rules.map((r, i) => (i === ruleIdx ? { ...r, [type]: [...r[type], "/new-path/"] } : r)));
  };

  const removePath = (ruleIdx: number, type: "allow" | "disallow", pathIdx: number) => {
    setRules(rules.map((r, i) => (i === ruleIdx ? { ...r, [type]: r[type].filter((_, j) => j !== pathIdx) } : r)));
  };

  const updatePath = (ruleIdx: number, type: "allow" | "disallow", pathIdx: number, value: string) => {
    setRules(rules.map((r, i) => (i === ruleIdx ? { ...r, [type]: r[type].map((p, j) => (j === pathIdx ? value : p)) } : r)));
  };

  const generateOutput = (): string => {
    let output = "# robots.txt\n# Generated by CodeSecAI Robots.txt Generator\n\n";
    rules.forEach((rule) => {
      output += `User-agent: ${rule.userAgent}\n`;
      rule.allow.forEach((p) => { output += `Allow: ${p}\n`; });
      rule.disallow.forEach((p) => { output += `Disallow: ${p}\n`; });
      if (crawlDelay) output += `Crawl-delay: ${crawlDelay}\n`;
      output += "\n";
    });
    if (sitemapUrl) output += `Sitemap: ${sitemapUrl}\n`;
    if (hostUrl) output += `Host: ${hostUrl}\n`;
    return output.trim();
  };

  const copyOutput = () => {
    navigator.clipboard.writeText(generateOutput());
    toast({ title: "robots.txt copied!" });
  };

  const commonAgents = ["*", "Googlebot", "Bingbot", "DuckDuckBot", "Slurp", "Baiduspider", "YandexBot", "GPTBot", "ChatGPT-User", "CCBot", "anthropic-ai"];

  return (
    <div className="space-y-6">
      {rules.map((rule, ruleIdx) => (
        <div key={ruleIdx} className="bg-muted/50 border rounded-lg p-4 space-y-3">
          <div className="flex items-center justify-between gap-2">
            <div className="flex items-center gap-2 flex-1">
              <label className="text-sm font-medium text-foreground shrink-0">User-Agent:</label>
              <Select value={rule.userAgent} onValueChange={(v) => updateUserAgent(ruleIdx, v)}>
                <SelectTrigger className="w-48"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {commonAgents.map((a) => <SelectItem key={a} value={a}>{a}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            {rules.length > 1 && (
              <Button size="sm" variant="ghost" onClick={() => removeRule(ruleIdx)} className="text-muted-foreground hover:text-destructive">
                <Trash2 className="h-3.5 w-3.5" />
              </Button>
            )}
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <div className="flex items-center justify-between mb-1">
                <span className="text-xs font-semibold text-green-600">Allow</span>
                <Button size="sm" variant="ghost" onClick={() => addPath(ruleIdx, "allow")} className="h-6 text-xs"><Plus className="h-3 w-3 mr-1" />Add</Button>
              </div>
              {rule.allow.map((path, pathIdx) => (
                <div key={pathIdx} className="flex items-center gap-1 mb-1">
                  <Input value={path} onChange={(e) => updatePath(ruleIdx, "allow", pathIdx, e.target.value)} className="h-8 text-xs font-mono" />
                  <Button size="sm" variant="ghost" onClick={() => removePath(ruleIdx, "allow", pathIdx)} className="h-8 w-8 p-0 text-muted-foreground hover:text-destructive shrink-0"><Trash2 className="h-3 w-3" /></Button>
                </div>
              ))}
            </div>
            <div>
              <div className="flex items-center justify-between mb-1">
                <span className="text-xs font-semibold text-red-600">Disallow</span>
                <Button size="sm" variant="ghost" onClick={() => addPath(ruleIdx, "disallow")} className="h-6 text-xs"><Plus className="h-3 w-3 mr-1" />Add</Button>
              </div>
              {rule.disallow.map((path, pathIdx) => (
                <div key={pathIdx} className="flex items-center gap-1 mb-1">
                  <Input value={path} onChange={(e) => updatePath(ruleIdx, "disallow", pathIdx, e.target.value)} className="h-8 text-xs font-mono" />
                  <Button size="sm" variant="ghost" onClick={() => removePath(ruleIdx, "disallow", pathIdx)} className="h-8 w-8 p-0 text-muted-foreground hover:text-destructive shrink-0"><Trash2 className="h-3 w-3" /></Button>
                </div>
              ))}
            </div>
          </div>
        </div>
      ))}

      <Button variant="outline" onClick={addRule} className="w-full"><Plus className="h-4 w-4 mr-2" />Add User-Agent Rule</Button>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div>
          <label className="text-sm font-medium text-foreground mb-1 block">Sitemap URL</label>
          <Input placeholder="https://example.com/sitemap.xml" value={sitemapUrl} onChange={(e) => setSitemapUrl(e.target.value)} />
        </div>
        <div>
          <label className="text-sm font-medium text-foreground mb-1 block">Crawl Delay (seconds)</label>
          <Input type="number" placeholder="10" value={crawlDelay} onChange={(e) => setCrawlDelay(e.target.value)} />
        </div>
        <div>
          <label className="text-sm font-medium text-foreground mb-1 block">Host URL</label>
          <Input placeholder="https://example.com" value={hostUrl} onChange={(e) => setHostUrl(e.target.value)} />
        </div>
      </div>

      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <h3 className="font-bold text-foreground">Preview</h3>
          <Button size="sm" variant="outline" onClick={copyOutput}><Copy className="h-3.5 w-3.5 mr-1" />Copy</Button>
        </div>
        <pre className="bg-muted rounded-lg p-4 text-xs font-mono overflow-x-auto whitespace-pre-wrap text-foreground">{generateOutput()}</pre>
      </div>
    </div>
  );
};

export default RobotsTxtGenerator;
